### ISSUE TITLE
Wrong media type (content-type) for JS files

### ISSUE THREAD

**Issue by mattbrundage** [sveinbjornt/DataURLToolkit#2]
The app is outputting a media type of "application/x-javascript" when I make a data URL of a JavaScript file. "application/x-javascript" is experimental and obsolete. Use "application/javascript" instead (per http://www.rfc-editor.org/rfc/rfc4329.txt)

**Comment by sveinbjornt** [comment]
Where in the web app? Mime types are handled by a third-party library.

**Comment by mattbrundage** [comment]
That was my suspicion -- that is was handled by a third party. I haven't dug too deeply in your code, but if you're getting the media type values from Apache, then this might just be a server configuration change. Not sure.

**Comment by mattbrundage** [comment]
Obsolete, I suppose.

**Comment by sveinbjornt** [comment]
Yeah, this software hasn't seen any love for a long time and is not likely to see it in the future. I'm done with Perl.
